dist: trusty
language: python

python:
  - "2.7"

install:
  - sh ckanext/gallery/tests/bin/build.sh

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.4"

script: coverage run --source=ckanext.gallery setup.py nosetests --ckan --with-pylons=ckanext/gallery/tests/bin/test.ini --nologcapture --debug=ckantest,ckanext.gallery --rednose

after_success: coveralls
